### ISSUE TITLE
Bug: Dialog crash on Electron v31.x

### ISSUE THREAD

**Issue by Aetherinox** [Araxeus/custom-electron-prompt#26]
This package works well on any version of Electron <= v30.3.0, however, when migrating over to Electron v31, clicking the close button in the top-right of the custom prompt dialog, the entire app itself will crash. 

If you utilize a button at the bottom of the prompt window to close it, it works fine, but that top-right button kills the app immediately and the process hangs in the background until killed by the task manager.

Created a fresh app with the following, and the bug exists there too:
```json
    "dependencies": {
        "custom-electron-prompt": "^1.5.7",
        "electron": "^31.0.0",
    }
```

<br />

### Works
![dmNefWORy3](https://github.com/user-attachments/assets/47e09e3e-227e-448a-b5b9-9c12bf4c7efa)

<br />

### Crashes
![IWVXNVXGNQ](https://github.com/user-attachments/assets/d17fc1b7-401e-469b-b78a-4f77f552401c)

<br >

---

<br>

### Electron v30
![Jtf6AOymwK](https://github.com/user-attachments/assets/93aca429-06c0-4c9f-a91b-aef142fd29d5)

<br />

### Electron v31
![IVXXylX3o7](https://github.com/user-attachments/assets/f5a2c143-edde-4d88-9aef-80e7b454f0d4)

<br >

---

<br>

This is on Windows 11 Pro. Have not tested on Linux yet.

Type of prompt doesn't matter either, have tested using `multiInput` and `input`

**Comment by Araxeus** [comment]
Weird, Electron didn't indicate any breaking changes - https://www.electronjs.org/blog/electron-31-0#breaking-changes
probably a bug on their end?

while this is fixed you could consider using [HTMLDialogElement](https://web.dev/learn/html/dialog)
or the [Popover API](https://web.dev/blog/popover-api)

for example see https://web.dev/patterns/components/dialog or https://css-tricks.com/replace-javascript-dialogs-html-dialog-element/

> [!NOTE]
> its probably related to: https://github.com/Araxeus/custom-electron-prompt/blob/ce677e8f4801baa2148ec5f88fd67198939bcfad/lib/index.js#L123-L137

**Comment by Aetherinox** [comment]
I actually went on Electron's Github looking for some specific breaking change, and I couldn't find anything either. So it's sort of weird that v31 is the one that decided to break it.

Thanks for the suggestion, I'll poke a look. This tool was just an easy way to implement dialogs without having to get over-complicated.

Right now it's working fine with Electron v30, but the main reason for updating electron was to keep up with vulnerabilities.

**Comment by Araxeus** [comment]
I will try looking into it more this week :)

(maybe related to https://github.com/electron/electron/issues/42562)

**Comment by Aetherinox** [comment]
Yeah, I went looking through their reported issues and that one caught my attention and I thought that may be related. But I hadn't had a chance to go ripping through Electron. I haven't done a lot of work with Electron on the back-end, so hunting it down would be a Where's Waldo moment.

**Comment by Araxeus** [comment]
can you publish your simple test app on github? (or electron fiddle)

**Comment by Aetherinox** [comment]
Sure, give me a few and I'll throw it up here:
https://github.com/Aetherinox/electron-prompts

**Comment by Araxeus** [comment]
i have reproduced it in fiddle too https://gist.github.com/Araxeus/6548ef4f3438d35d1713d5fd69c3b494

**Comment by Aetherinox** [comment]
Ah ok, I just uploaded mine.

I kept the custom .css file in there as well, since it's part of the dialog system, wasn't sure if that would also play a role. So just in case.

My demo app is also crashing on exit.

**Comment by Araxeus** [comment]
It happens because [`BrowserWindow.destroy()`](https://www.electronjs.org/docs/latest/api/browser-window#windestroy) is called (on the child prompt window)

if we change `destroy` to [`BrowserWindow.close()`](https://www.electronjs.org/docs/latest/api/browser-window#winclose) then Electron stops crashing. 

I will create a bug report on Electron's repo (https://github.com/electron/electron/issues/42975) and create a temporary hotfix version of custom-electron-prompt

**Comment by Aetherinox** [comment]
Nice. Really appreciate the quick attention. Like I said, not a huge deal, but I imagine when Electron hits v40, it might cause concerns for security on apps having to stay behind.

Thanks again.

**Comment by Araxeus** [comment]
[v1.5.8](https://github.com/Araxeus/custom-electron-prompt/releases/tag/v1.5.8) fixes the issue
(the electron issue is still open and unresolved)

**Comment by Aetherinox** [comment]
Just tested it out and it works great. Really appreciate it. I'm now on electron v31 without issues. Much thanks.
